#!/usr/bin/env node

const GEN_STAFF_COUNT = 100;
const staffs = [];

for (let i = 0; i < GEN_STAFF_COUNT; i++) {
  const staff = {
    name: `staff${i}`
  };
  staffs[i] = staff;
}

console.log(JSON.stringify(staffs));
